# Generated by Django 5.2.16 on 2026-08-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='S4Pokedex',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('points', models.IntegerField()),
                ('sprite_id', models.CharField(max_length=64)),
                ('pokedex_num', models.IntegerField(null=True)),
                ('types', models.JSONField(default=list)),
                ('base_hp', models.IntegerField(null=True)),
                ('base_atk', models.IntegerField(null=True)),
                ('base_def', models.IntegerField(null=True)),
                ('base_spa', models.IntegerField(null=True)),
                ('base_spd', models.IntegerField(null=True)),
                ('base_spe', models.IntegerField(null=True)),
                ('abilities', models.JSONField(default=dict)),
                ('height_m', models.FloatField(null=True)),
                ('weight_kg', models.FloatField(null=True)),
                ('color', models.CharField(max_length=32, null=True)),
                ('evos', models.JSONField(default=list)),
                ('egg_groups', models.JSONField(default=list)),
                ('tier', models.CharField(max_length=16, null=True)),
            ],
            options={
                'verbose_name_plural': 'S4 pokedex',
                'db_table': 's4_pokedex',
            },
        ),
    ]
