# Generated by Django 5.2.16 on 2026-08-27 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='S4FreeAgencyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach', models.CharField(max_length=64)),
                ('team_name', models.CharField(max_length=128, null=True)),
                ('drops', models.JSONField(default=list, help_text='List of {name, points}.')),
                ('pickups', models.JSONField(default=list, help_text='List of {name, points}.')),
            ],
            options={
                'verbose_name_plural': 'S4 free agency log',
                'db_table': 's4_free_agency_log',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='S4Rosters',
            fields=[
                ('coach_name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=128, null=True)),
                ('logo', models.CharField(default='', max_length=256)),
                ('pokemon', models.JSONField(default=list, help_text='List of {name, points}.')),
                ('free_agents_used', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'S4 rosters',
                'db_table': 's4_rosters',
            },
        ),
        migrations.CreateModel(
            name='S4Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('week_label', models.CharField(max_length=32)),
                ('match_index', models.IntegerField(help_text="Position of this match within its week's matches list.")),
                ('player1', models.CharField(max_length=64)),
                ('player2', models.CharField(max_length=64)),
                ('replay_url', models.CharField(max_length=512, null=True)),
                ('winner', models.CharField(max_length=8, null=True)),
                ('margin', models.IntegerField(null=True)),
                ('stats', models.JSONField(help_text="{'player1': [...], 'player2': [...]} per-Pokemon stat dicts.", null=True)),
            ],
            options={
                'verbose_name_plural': 'S4 schedule',
                'db_table': 's4_schedule',
                'ordering': ['week', 'match_index'],
                'unique_together': {('week', 'match_index')},
            },
        ),
    ]
