# Generated by Django 5.2.16 on 2026-08-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_s4freeagencylog_s4rosters_s4schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='S1FreeAgencyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach', models.CharField(max_length=64)),
                ('team_name', models.CharField(max_length=128, null=True)),
                ('drops', models.JSONField(default=list, help_text='List of {name, points}.')),
                ('pickups', models.JSONField(default=list, help_text='List of {name, points}.')),
            ],
            options={
                'verbose_name_plural': 'S1 free agency log',
                'db_table': 's1_free_agency_log',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='S1Pokedex',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('points', models.IntegerField()),
                ('sprite_id', models.CharField(max_length=64)),
                ('pokedex_num', models.IntegerField(null=True)),
                ('types', models.JSONField(default=list)),
                ('base_hp', models.IntegerField(null=True)),
                ('base_atk', models.IntegerField(null=True)),
                ('base_def', models.IntegerField(null=True)),
                ('base_spa', models.IntegerField(null=True)),
                ('base_spd', models.IntegerField(null=True)),
                ('base_spe', models.IntegerField(null=True)),
                ('abilities', models.JSONField(default=dict)),
                ('height_m', models.FloatField(null=True)),
                ('weight_kg', models.FloatField(null=True)),
                ('color', models.CharField(max_length=32, null=True)),
                ('evos', models.JSONField(default=list)),
                ('egg_groups', models.JSONField(default=list)),
                ('tier', models.CharField(max_length=16, null=True)),
            ],
            options={
                'verbose_name_plural': 'S1 pokedex',
                'db_table': 's1_pokedex',
            },
        ),
        migrations.CreateModel(
            name='S1Rosters',
            fields=[
                ('coach_name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=128, null=True)),
                ('logo', models.CharField(default='', max_length=256)),
                ('pokemon', models.JSONField(default=list, help_text='List of {name, points}.')),
                ('free_agents_used', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'S1 rosters',
                'db_table': 's1_rosters',
            },
        ),
        migrations.CreateModel(
            name='S2FreeAgencyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach', models.CharField(max_length=64)),
                ('team_name', models.CharField(max_length=128, null=True)),
                ('drops', models.JSONField(default=list, help_text='List of {name, points}.')),
                ('pickups', models.JSONField(default=list, help_text='List of {name, points}.')),
            ],
            options={
                'verbose_name_plural': 'S2 free agency log',
                'db_table': 's2_free_agency_log',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='S2Pokedex',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('points', models.IntegerField()),
                ('sprite_id', models.CharField(max_length=64)),
                ('pokedex_num', models.IntegerField(null=True)),
                ('types', models.JSONField(default=list)),
                ('base_hp', models.IntegerField(null=True)),
                ('base_atk', models.IntegerField(null=True)),
                ('base_def', models.IntegerField(null=True)),
                ('base_spa', models.IntegerField(null=True)),
                ('base_spd', models.IntegerField(null=True)),
                ('base_spe', models.IntegerField(null=True)),
                ('abilities', models.JSONField(default=dict)),
                ('height_m', models.FloatField(null=True)),
                ('weight_kg', models.FloatField(null=True)),
                ('color', models.CharField(max_length=32, null=True)),
                ('evos', models.JSONField(default=list)),
                ('egg_groups', models.JSONField(default=list)),
                ('tier', models.CharField(max_length=16, null=True)),
            ],
            options={
                'verbose_name_plural': 'S2 pokedex',
                'db_table': 's2_pokedex',
            },
        ),
        migrations.CreateModel(
            name='S2Rosters',
            fields=[
                ('coach_name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=128, null=True)),
                ('logo', models.CharField(default='', max_length=256)),
                ('pokemon', models.JSONField(default=list, help_text='List of {name, points}.')),
                ('free_agents_used', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'S2 rosters',
                'db_table': 's2_rosters',
            },
        ),
        migrations.CreateModel(
            name='S3FreeAgencyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach', models.CharField(max_length=64)),
                ('team_name', models.CharField(max_length=128, null=True)),
                ('drops', models.JSONField(default=list, help_text='List of {name, points}.')),
                ('pickups', models.JSONField(default=list, help_text='List of {name, points}.')),
            ],
            options={
                'verbose_name_plural': 'S3 free agency log',
                'db_table': 's3_free_agency_log',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='S3Pokedex',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('points', models.IntegerField()),
                ('sprite_id', models.CharField(max_length=64)),
                ('pokedex_num', models.IntegerField(null=True)),
                ('types', models.JSONField(default=list)),
                ('base_hp', models.IntegerField(null=True)),
                ('base_atk', models.IntegerField(null=True)),
                ('base_def', models.IntegerField(null=True)),
                ('base_spa', models.IntegerField(null=True)),
                ('base_spd', models.IntegerField(null=True)),
                ('base_spe', models.IntegerField(null=True)),
                ('abilities', models.JSONField(default=dict)),
                ('height_m', models.FloatField(null=True)),
                ('weight_kg', models.FloatField(null=True)),
                ('color', models.CharField(max_length=32, null=True)),
                ('evos', models.JSONField(default=list)),
                ('egg_groups', models.JSONField(default=list)),
                ('tier', models.CharField(max_length=16, null=True)),
            ],
            options={
                'verbose_name_plural': 'S3 pokedex',
                'db_table': 's3_pokedex',
            },
        ),
        migrations.CreateModel(
            name='S3Rosters',
            fields=[
                ('coach_name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=128, null=True)),
                ('logo', models.CharField(default='', max_length=256)),
                ('pokemon', models.JSONField(default=list, help_text='List of {name, points}.')),
                ('free_agents_used', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'S3 rosters',
                'db_table': 's3_rosters',
            },
        ),
        migrations.CreateModel(
            name='S1Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('week_label', models.CharField(max_length=32)),
                ('match_index', models.IntegerField(help_text="Position of this match within its week's matches list.")),
                ('player1', models.CharField(max_length=64)),
                ('player2', models.CharField(max_length=64)),
                ('replay_url', models.CharField(max_length=512, null=True)),
                ('winner', models.CharField(max_length=8, null=True)),
                ('margin', models.IntegerField(null=True)),
                ('stats', models.JSONField(help_text="{'player1': [...], 'player2': [...]} per-Pokemon stat dicts.", null=True)),
            ],
            options={
                'verbose_name_plural': 'S1 schedule',
                'db_table': 's1_schedule',
                'ordering': ['week', 'match_index'],
                'unique_together': {('week', 'match_index')},
            },
        ),
        migrations.CreateModel(
            name='S2Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('week_label', models.CharField(max_length=32)),
                ('match_index', models.IntegerField(help_text="Position of this match within its week's matches list.")),
                ('player1', models.CharField(max_length=64)),
                ('player2', models.CharField(max_length=64)),
                ('replay_url', models.CharField(max_length=512, null=True)),
                ('winner', models.CharField(max_length=8, null=True)),
                ('margin', models.IntegerField(null=True)),
                ('stats', models.JSONField(help_text="{'player1': [...], 'player2': [...]} per-Pokemon stat dicts.", null=True)),
            ],
            options={
                'verbose_name_plural': 'S2 schedule',
                'db_table': 's2_schedule',
                'ordering': ['week', 'match_index'],
                'unique_together': {('week', 'match_index')},
            },
        ),
        migrations.CreateModel(
            name='S3Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('week_label', models.CharField(max_length=32)),
                ('match_index', models.IntegerField(help_text="Position of this match within its week's matches list.")),
                ('player1', models.CharField(max_length=64)),
                ('player2', models.CharField(max_length=64)),
                ('replay_url', models.CharField(max_length=512, null=True)),
                ('winner', models.CharField(max_length=8, null=True)),
                ('margin', models.IntegerField(null=True)),
                ('stats', models.JSONField(help_text="{'player1': [...], 'player2': [...]} per-Pokemon stat dicts.", null=True)),
            ],
            options={
                'verbose_name_plural': 'S3 schedule',
                'db_table': 's3_schedule',
                'ordering': ['week', 'match_index'],
                'unique_together': {('week', 'match_index')},
            },
        ),
    ]
