# Generated by Django 5.2.16 on 2026-08-30 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_s1freeagencylog_s1pokedex_s1rosters_s2freeagencylog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='S1Accolades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finals', models.JSONField(default=None, help_text="{'team1': ..., 'team2': ..., 'winner': ...} or null.", null=True)),
                ('player_awards', models.JSONField(default=list, help_text='List of {category, entries}.')),
                ('pokemon_awards', models.JSONField(default=list, help_text='List of {category, entries}.')),
                ('match_awards', models.JSONField(default=list, help_text='List of {category, entries}.')),
                ('community', models.JSONField(default=list, help_text='List of {category, entries}.')),
            ],
            options={
                'verbose_name_plural': 'S1 accolades',
                'db_table': 's1_accolades',
            },
        ),
        migrations.CreateModel(
            name='S2Accolades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finals', models.JSONField(default=None, help_text="{'team1': ..., 'team2': ..., 'winner': ...} or null.", null=True)),
                ('player_awards', models.JSONField(default=list, help_text='List of {category, entries}.')),
                ('pokemon_awards', models.JSONField(default=list, help_text='List of {category, entries}.')),
                ('match_awards', models.JSONField(default=list, help_text='List of {category, entries}.')),
                ('community', models.JSONField(default=list, help_text='List of {category, entries}.')),
            ],
            options={
                'verbose_name_plural': 'S2 accolades',
                'db_table': 's2_accolades',
            },
        ),
        migrations.CreateModel(
            name='S3Accolades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finals', models.JSONField(default=None, help_text="{'team1': ..., 'team2': ..., 'winner': ...} or null.", null=True)),
                ('player_awards', models.JSONField(default=list, help_text='List of {category, entries}.')),
                ('pokemon_awards', models.JSONField(default=list, help_text='List of {category, entries}.')),
                ('match_awards', models.JSONField(default=list, help_text='List of {category, entries}.')),
                ('community', models.JSONField(default=list, help_text='List of {category, entries}.')),
            ],
            options={
                'verbose_name_plural': 'S3 accolades',
                'db_table': 's3_accolades',
            },
        ),
        migrations.CreateModel(
            name='S4Accolades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finals', models.JSONField(default=None, help_text="{'team1': ..., 'team2': ..., 'winner': ...} or null.", null=True)),
                ('player_awards', models.JSONField(default=list, help_text='List of {category, entries}.')),
                ('pokemon_awards', models.JSONField(default=list, help_text='List of {category, entries}.')),
                ('match_awards', models.JSONField(default=list, help_text='List of {category, entries}.')),
                ('community', models.JSONField(default=list, help_text='List of {category, entries}.')),
            ],
            options={
                'verbose_name_plural': 'S4 accolades',
                'db_table': 's4_accolades',
            },
        ),
        migrations.AddField(
            model_name='s1schedule',
            name='scheduled_day',
            field=models.DateField(blank=True, help_text='Coach-proposed day to play, before a replay is submitted.', null=True),
        ),
        migrations.AddField(
            model_name='s2schedule',
            name='scheduled_day',
            field=models.DateField(blank=True, help_text='Coach-proposed day to play, before a replay is submitted.', null=True),
        ),
        migrations.AddField(
            model_name='s3schedule',
            name='scheduled_day',
            field=models.DateField(blank=True, help_text='Coach-proposed day to play, before a replay is submitted.', null=True),
        ),
        migrations.AddField(
            model_name='s4schedule',
            name='scheduled_day',
            field=models.DateField(blank=True, help_text='Coach-proposed day to play, before a replay is submitted.', null=True),
        ),
    ]
